In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
sys.path.append(module_path)

from bsa.scripts.grid_search import load_and_preprocess, get_horizon

Device:  cpu

In [2]:
(x_train, y_train), (x_test, y_test), (x_val, y_val) = load_and_preprocess()

In [3]:
print("Training features shape: ", x_train.shape)
print("Training labels shape: ", y_train.shape)
print("Testing features shape: ", x_test.shape)
print("Testing labels shape: ", y_test.shape)
print("Validation features shape: ", x_val.shape)
print("Validation labels shape: ", y_val.shape)

Training features shape:  (40663, 324)
Training labels shape:  (40663, 3)
Testing features shape:  (20684, 324)
Testing labels shape:  (20684, 3)
Validation features shape:  (20469, 324)
Validation labels shape:  (20469, 3)

In [4]:
(x_train, y_train), (x_test, y_test), (x_val, y_val) = get_horizon(x_train, y_train, x_test, y_test, x_val, y_val, 3)

/home/tonyzou/bankruptcy-survival-analysis/bsa/dataset/data_loader.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['HBankrupt'] = ((y['T'] <= (horizon + 1)) & bankrupted_filter).astype(int)
/home/tonyzou/bankruptcy-survival-analysis/bsa/dataset/data_loader.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['HBankrupt'] = ((y['T'] <= (horizon + 1)) & bankrupted_filter).astype(int)
/home/tonyzou/bankruptcy-survival-analysis/bsa/dataset/data_loader.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['HBankrupt'] = ((y['T'] <= (horizon + 1)) & bankrupted_filter).astype(int)

In [7]:
 , y_train.loc[62732]

       IBankrupt   T  E  HBankrupt
fyear
1997           0  21  0          0
1998           0  20  0          0
1999           0  19  0          0
2000           0  18  0          0
2001           0  17  0          0
2002           0  16  0          0
2003           0  15  0          0
2004           0  14  0          0
2005           0  13  0          0
2006           0  12  0          0
2007           0  11  0          0
2008           0  10  0          0
2009           0   9  0          0
2010           0   8  0          0
2011           0   7  0          0
2012           0   6  0          0
2013           0   5  0          0
2014           0   4  0          0